TEST_USER_ID = "test_user_id"
TEST_USER_EMAIL = "testuser@example.com"
TEST_AGENT_ID = "sender_agent_id"
TEST_AGENCY_ID = "test_agency_id"
TEST_ENCRYPTION_KEY = b"Xf0Wk0vLLd8nKS1QKv9aN0I-GrFospseEFhich6BdNU="
