name: Publish to Google Artifact Registry

on:
  release:
    types:
      - created

env:
  PROJECT_ID: XXX
  SERVICE_ACCOUNT: XXX
  WORKLOAD_IDENTITY_PROVIDER: XXX
  REPOSITORY_URL: XXX

jobs:
  # Build the python package file and push to Google Artifacts Repository
  push-package:
    name: Build and publish the Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - name: Build Package
        run: poetry build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Upload to Artifact Registry
        run: |
          python -m pip install keyrings.google-artifactregistry-auth
          python -m pip install twine
          python -m twine upload --repository-url $REPOSITORY_URL dist/*
